name: Android Instrumented Tests
on: workflow_dispatch

jobs:
  android-instrumented-tests:
    name: Android Instrumented Tests
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86_64
          script: ./gradlew copyBrandingToCommonResources connectedDebugAndroidTest

      - name: Uploads test reports
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: android-instrumented-tests-report
          path: composeApp/build/reports/androidTests/connected/debug/
