name: Desktop package apps
on: workflow_dispatch

jobs:
  package:
    name: Package desktop apps
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Package app(macOS)
        if: runner.os == 'macOS'
        run: ./gradlew copyBrandingToCommonResources packageDmg -Porganization=ooni

      - name: Package Exe(Windows)
        if: runner.os == 'Windows'
        run: ./gradlew copyBrandingToCommonResources packageExe -Porganization=ooni

      - name: Package Exe(Linux)
        if: runner.os == 'Linux'
        run: ./gradlew copyBrandingToCommonResources packageDeb packageAppImage -Porganization=ooni

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: desktopApps
          path: composeApp/build/compose/binaries
