name: Publish OONI Probe on Huawei AppGallery

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish OONI Probe Android on Huawei AppGallery
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Decode Android keystore
        run: echo "${{ secrets.OONI_ANDROID_KEY_STOREFILE }}" | base64 --decode > composeApp/upload-keystore.jks

      - name: Publish to Huawei AppGallery
        env:
          ANDROID_KEYSTORE_FILE: upload-keystore.jks
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.OONI_ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_PASSWORD: ${{ secrets.OONI_ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.OONI_ANDROID_KEY_ALIAS }}
          APP_ID: ${{ secrets.APP_GALLERY_APP_ID }}
          CLIENT_ID: ${{ secrets.APP_GALLERY_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.APP_GALLERY_CLIENT_SECRET }}
          APK_PATH: composeApp/build/outputs/bundle/fullRelease/composeApp-full-release.aab
        run: bundle exec fastlane android publish_app_gallery organization:ooni app_id:$APP_ID client_id:$CLIENT_ID client_secret:$CLIENT_SECRET apk_path:$APK_PATH
