name: Publish Android

on:
  workflow_dispatch:
    inputs:
      track:
        description: 'Google Play Track'
        required: true
        type: choice
        default: 'alpha'
        options:
          - internal
          - alpha
          - beta
          - production
      ooniProbe:
        description: 'OONI Probe Android'
        required: false
        type: boolean
      newsMediaScan:
        description: 'News Media Scan Android'
        required: false
        type: boolean

jobs:
  publishOoniProbe:
    name: Publish OONI Probe Android
    if: ${{ inputs.ooniProbe }}
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Publish
        env:
          TRACK: ${{ inputs.track }}
        run: bundle exec fastlane android publish track:$TRACK organization:ooni

  publishNewsMediaScan:
    name: Publish News Media Scan Android
    if: ${{ inputs.newsMediaScan }}
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Publish
        env:
          TRACK: ${{ inputs.track }}
        run: bundle exec fastlane android publish track:$TRACK organization:dw
