name: Publish iOS Apps

on:
  workflow_dispatch:
    inputs:
      ooniProbe:
        description: 'OONI Probe iOS'
        required: false
        type: boolean
      newsMediaScan:
        description: 'News Media Scan iOS'
        required: false
        type: boolean

jobs:
  publishOoniProbe:
    name: Publish OONI Probe iOS
    if: ${{ inputs.ooniProbe }}
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Xcode Cache
        uses: irgaly/xcode-cache@v1
        with:
          key: xcode-cache-deriveddata-${{ github.workflow }}-ooni-${{ github.sha }}
          restore-keys: xcode-cache-deriveddata-${{ github.workflow }}-ooni-

      - name: Publish iOS App
        run: bundle exec fastlane ios publish organization:ooni

      - name: Upload debug symbols
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG_SLUG: ${{ secrets.SENTRY_ORG_SLUG }}
          SENTRY_PROJECT_SLUG: ${{ secrets.SENTRY_PROJECT_SLUG_IOS }}
        run: bundle exec fastlane ios sentry_upload_debug_symbols auth_token:$SENTRY_AUTH_TOKEN org_slug:$SENTRY_ORG_SLUG project_slug:$SENTRY_PROJECT_SLUG

  publishNewsMediaScan:
    name: Publish NewsMediaScan iOS
    if: ${{ inputs.ooniProbe }}
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Xcode Cache
        uses: irgaly/xcode-cache@v1
        with:
          key: xcode-cache-deriveddata-${{ github.workflow }}-dw-${{ github.sha }}
          restore-keys: xcode-cache-deriveddata-${{ github.workflow }}-dw-

      - name: Publish iOS App
        run: bundle exec fastlane ios publish organization:dw

      - name: Upload debug symbols
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG_SLUG: ${{ secrets.SENTRY_ORG_SLUG }}
          SENTRY_PROJECT_SLUG: ${{ secrets.SENTRY_PROJECT_SLUG_IOS }}
        run: bundle exec fastlane sentry_upload_debug_symbols auth_token:$SENTRY_AUTH_TOKEN org_slug:$SENTRY_ORG_SLUG project_slug:$SENTRY_PROJECT_SLUG
