name: Publish OONI Probe on Huawei AppGallery

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish OONI Probe Android on Huawei AppGallery
    if: ${{ inputs.ooniProbe }}
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      # TODO
