name: Publish Android on Google Play

on:
  workflow_dispatch:
    inputs:
      track:
        description: 'Google Play Track'
        required: true
        type: choice
        default: 'alpha'
        options:
          - internal
          - alpha
          - beta
          - production
      versionCode:
        description: 'New version code'
        required: true
        type: number
      ooniProbe:
        description: 'OONI Probe Android'
        required: false
        type: boolean
      newsMediaScan:
        description: 'News Media Scan Android'
        required: false
        type: boolean

jobs:
  publishOoniProbe:
    name: Publish OONI Probe Android
    if: ${{ inputs.ooniProbe }}
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Decode Android keystore
        run: echo "${{ secrets.OONI_ANDROID_KEY_STOREFILE }}" | base64 --decode > composeApp/upload-keystore.jks

      - name: Decode Service Account file
        run: echo "${{ secrets.OONI_ANDROID_SERVICE_ACCOUNT }}" | base64 --decode > key.json

      - name: Publish
        env:
          TRACK: ${{ inputs.track }}
          ANDROID_KEYSTORE_FILE: upload-keystore.jks
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.OONI_ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_PASSWORD: ${{ secrets.OONI_ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.OONI_ANDROID_KEY_ALIAS }}
        run: bundle exec fastlane android publish track:$TRACK organization:ooni json_key:key.json

  publishNewsMediaScan:
    name: Publish News Media Scan Android
    if: ${{ inputs.newsMediaScan }}
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      # TODO: Get Android keystore and Google Play Service Account

      - name: Publish
        env:
          TRACK: ${{ inputs.track }}
          VERSION_CODE: ${{ inputs.versionCode }}
        run: bundle exec fastlane android publish track:$TRACK version_code:$VERSION_CODE organization:dw json_key:key.json
