name: Publish OONI Probe on Huawei AppGallery

on:
  workflow_dispatch:
    inputs:
      ooniProbe:
        description: 'OONI Probe Android'
        required: false
        type: boolean

jobs:
  publish:
    name: Publish OONI Probe Android on Huawei AppGallery
    if: ${{ inputs.ooniProbe }}
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Publish to Huawei AppGallery
        env:
          APP_ID: ${{ secrets.APP_GALLERY_APP_ID }}
          CLIENT_ID: ${{ secrets.APP_GALLERY_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.APP_GALLERY_CLIENT_SECRET }}
          APK_PATH: composeApp/build/outputs/bundle/fullRelease/composeApp-full-release.aab
        run: bundle exec fastlane android publish_app_gallery organization:ooni app_id:$APP_ID client_id:$CLIENT_ID client_secret:$CLIENT_SECRET apk_path:$APK_PATH
