name: Run Android Instrumented Tests
on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  instrumentation-tests:
    name: Run Android Instrumented Tests
    runs-on: macos-latest

    strategy:
      matrix:
        license: [ full, fdroid ]
        organization: [ ooni, dw ]
        exclude:
          - license: fdroid
            organization: dw

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build APKs
        run: ./gradlew copyBrandingToCommonResources assemble${{ matrix.license }}Debug assemble${{ matrix.license }}DebugAndroidTest -Porganization=${{ matrix.organization }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 495.0.0'

      - name: GCloud authentication
        env:
          INPUT_SERVICE_CREDENTIALS_FILE_CONTENT: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          GOOGLE_APPLICATION_CREDENTIALS: service_credentials_content.json
        run: |
          cat <<< "${INPUT_SERVICE_CREDENTIALS_FILE_CONTENT}" > service_credentials_content.json
          gcloud auth activate-service-account --key-file=service_credentials_content.json

      - name: Firebase Test Lab
        run: >-
          LABEL=$(git show -s --format='%H')
          gcloud firebase test android run
          --type instrumentation
          --app composeApp/build/outputs/apk/${{ matrix.license }}/debug/composeApp-${{ matrix.license }}-universal-debug.apk
          --test composeApp/build/outputs/apk/androidTest/${{ matrix.license }}/debug/composeApp-${{ matrix.license }}-debug-androidTest.apk
          --device model=MediumPhone.arm,version=29,locale=en,orientation=portrait
          --timeout 180s
          --num-flaky-test-attempts=2
          --client-details matrixLabel="$LABEL"
          --use-orchestrator
          --environment-variables clearPackageData=true
          --project ooniprobe-android
          --test-targets "package org.ooni.probe.uitesting"
